//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4_4E")]
        public string battlemap {
            get {
                return ((string)(this["battlemap"]));
            }
            set {
                this["battlemap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("第一梯队")]
        public string mainteam {
            get {
                return ((string)(this["mainteam"]));
            }
            set {
                this["mainteam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("第三梯队")]
        public string supportteam {
            get {
                return ((string)(this["supportteam"]));
            }
            set {
                this["supportteam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Fix {
            get {
                return ((bool)(this["Fix"]));
            }
            set {
                this["Fix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Fixmaxtime {
            get {
                return ((int)(this["Fixmaxtime"]));
            }
            set {
                this["Fixmaxtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Fixmintime {
            get {
                return ((int)(this["Fixmintime"]));
            }
            set {
                this["Fixmintime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280*720")]
        public string resolution {
            get {
                return ((string)(this["resolution"]));
            }
            set {
                this["resolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugMode {
            get {
                return ((bool)(this["DebugMode"]));
            }
            set {
                this["DebugMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double WaitTime {
            get {
                return ((double)(this["WaitTime"]));
            }
            set {
                this["WaitTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTimeU {
            get {
                return ((bool)(this["FirstTimeU"]));
            }
            set {
                this["FirstTimeU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HomePage0 {
            get {
                return ((string)(this["HomePage0"]));
            }
            set {
                this["HomePage0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3ac2f7")]
        public string HomePage1 {
            get {
                return ((string)(this["HomePage1"]));
            }
            set {
                this["HomePage1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffffff")]
        public string HomePage2 {
            get {
                return ((string)(this["HomePage2"]));
            }
            set {
                this["HomePage2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("292829")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("de3500")]
        public string UrgentTask {
            get {
                return ((string)(this["UrgentTask"]));
            }
            set {
                this["UrgentTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8cca10")]
        public string selfdiscipline {
            get {
                return ((string)(this["selfdiscipline"]));
            }
            set {
                this["selfdiscipline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffba00")]
        public string normal {
            get {
                return ((string)(this["normal"]));
            }
            set {
                this["normal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("94c6f7")]
        public string AirPort {
            get {
                return ((string)(this["AirPort"]));
            }
            set {
                this["AirPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ff5500")]
        public string Battle0 {
            get {
                return ((string)(this["Battle0"]));
            }
            set {
                this["Battle0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffba00")]
        public string TeamSelect {
            get {
                return ((string)(this["TeamSelect"]));
            }
            set {
                this["TeamSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("313531")]
        public string TeamListSelect0 {
            get {
                return ((string)(this["TeamListSelect0"]));
            }
            set {
                this["TeamListSelect0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffaa00")]
        public string LogisticsTeamColor {
            get {
                return ((string)(this["LogisticsTeamColor"]));
            }
            set {
                this["LogisticsTeamColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f7ae00")]
        public string BattleSelectColor {
            get {
                return ((string)(this["BattleSelectColor"]));
            }
            set {
                this["BattleSelectColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffba00")]
        public string TeamListSelect1 {
            get {
                return ((string)(this["TeamListSelect1"]));
            }
            set {
                this["TeamListSelect1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffba00")]
        public string TeamListSelect2 {
            get {
                return ((string)(this["TeamListSelect2"]));
            }
            set {
                this["TeamListSelect2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RandomNotes {
            get {
                return ((bool)(this["RandomNotes"]));
            }
            set {
                this["RandomNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("第一梯队")]
        public string AutoTeam1 {
            get {
                return ((string)(this["AutoTeam1"]));
            }
            set {
                this["AutoTeam1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("第二梯队")]
        public string AutoTeam2 {
            get {
                return ((string)(this["AutoTeam2"]));
            }
            set {
                this["AutoTeam2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("第三梯队")]
        public string AutoTeam3 {
            get {
                return ((string)(this["AutoTeam3"]));
            }
            set {
                this["AutoTeam3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("第四梯队")]
        public string AutoTeam4 {
            get {
                return ((string)(this["AutoTeam4"]));
            }
            set {
                this["AutoTeam4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1_4E")]
        public string AutoMap {
            get {
                return ((string)(this["AutoMap"]));
            }
            set {
                this["AutoMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Simulator {
            get {
                return ((int)(this["Simulator"]));
            }
            set {
                this["Simulator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OsType {
            get {
                return ((int)(this["OsType"]));
            }
            set {
                this["OsType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool supplies {
            get {
                return ((bool)(this["supplies"]));
            }
            set {
                this["supplies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RoundInterval {
            get {
                return ((int)(this["RoundInterval"]));
            }
            set {
                this["RoundInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BattleLoopUnLockWindows {
            get {
                return ((bool)(this["BattleLoopUnLockWindows"]));
            }
            set {
                this["BattleLoopUnLockWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BindWindowsType {
            get {
                return ((int)(this["BindWindowsType"]));
            }
            set {
                this["BindWindowsType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("代号01")]
        public string LogisticsTask1 {
            get {
                return ((string)(this["LogisticsTask1"]));
            }
            set {
                this["LogisticsTask1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("代号14")]
        public string LogisticsTask2 {
            get {
                return ((string)(this["LogisticsTask2"]));
            }
            set {
                this["LogisticsTask2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("代号17")]
        public string LogisticsTask3 {
            get {
                return ((string)(this["LogisticsTask3"]));
            }
            set {
                this["LogisticsTask3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("代号22")]
        public string LogisticsTask4 {
            get {
                return ((string)(this["LogisticsTask4"]));
            }
            set {
                this["LogisticsTask4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TeamListSelect3 {
            get {
                return ((string)(this["TeamListSelect3"]));
            }
            set {
                this["TeamListSelect3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dismantlegun {
            get {
                return ((bool)(this["dismantlegun"]));
            }
            set {
                this["dismantlegun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChangeGun {
            get {
                return ((bool)(this["ChangeGun"]));
            }
            set {
                this["ChangeGun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetMap {
            get {
                return ((bool)(this["SetMap"]));
            }
            set {
                this["SetMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LockWindows {
            get {
                return ((bool)(this["LockWindows"]));
            }
            set {
                this["LockWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int FixMinPercentage {
            get {
                return ((int)(this["FixMinPercentage"]));
            }
            set {
                this["FixMinPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int FixMaxPercentage {
            get {
                return ((int)(this["FixMaxPercentage"]));
            }
            set {
                this["FixMaxPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int FixType {
            get {
                return ((int)(this["FixType"]));
            }
            set {
                this["FixType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public double FindTeamSlectStrSim {
            get {
                return ((double)(this["FindTeamSlectStrSim"]));
            }
            set {
                this["FindTeamSlectStrSim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string FindTeamSlectStrColorOffset {
            get {
                return ((string)(this["FindTeamSlectStrColorOffset"]));
            }
            set {
                this["FindTeamSlectStrColorOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SetMapType {
            get {
                return ((int)(this["SetMapType"]));
            }
            set {
                this["SetMapType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SimulatorHomeCapX1 {
            get {
                return ((int)(this["SimulatorHomeCapX1"]));
            }
            set {
                this["SimulatorHomeCapX1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int SimulatorHomeCapX2 {
            get {
                return ((int)(this["SimulatorHomeCapX2"]));
            }
            set {
                this["SimulatorHomeCapX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SimulatorHomeCapY1 {
            get {
                return ((int)(this["SimulatorHomeCapY1"]));
            }
            set {
                this["SimulatorHomeCapY1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int SimulatorHomeCapY2 {
            get {
                return ((int)(this["SimulatorHomeCapY2"]));
            }
            set {
                this["SimulatorHomeCapY2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SimulatorHomeCheckX1 {
            get {
                return ((int)(this["SimulatorHomeCheckX1"]));
            }
            set {
                this["SimulatorHomeCheckX1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SimulatorHomeCheckX2 {
            get {
                return ((int)(this["SimulatorHomeCheckX2"]));
            }
            set {
                this["SimulatorHomeCheckX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SimulatorHomeCheckY1 {
            get {
                return ((int)(this["SimulatorHomeCheckY1"]));
            }
            set {
                this["SimulatorHomeCheckY1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SimulatorHomeCheckY2 {
            get {
                return ((int)(this["SimulatorHomeCheckY2"]));
            }
            set {
                this["SimulatorHomeCheckY2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SimulatorHomeCheckTime {
            get {
                return ((int)(this["SimulatorHomeCheckTime"]));
            }
            set {
                this["SimulatorHomeCheckTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("343")]
        public int GameIconX {
            get {
                return ((int)(this["GameIconX"]));
            }
            set {
                this["GameIconX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("203")]
        public int GameIconY {
            get {
                return ((int)(this["GameIconY"]));
            }
            set {
                this["GameIconY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Team_SerrorTime {
            get {
                return ((int)(this["Team_SerrorTime"]));
            }
            set {
                this["Team_SerrorTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int LogisticFinishWaittingTime {
            get {
                return ((int)(this["LogisticFinishWaittingTime"]));
            }
            set {
                this["LogisticFinishWaittingTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LogisticLoopTimeMAX {
            get {
                return ((int)(this["LogisticLoopTimeMAX"]));
            }
            set {
                this["LogisticLoopTimeMAX"] = value;
            }
        }
    }
}
